import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Foody</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
          <ul>
            <Link href='/'><li>HOME</li></Link>
            <Link href='/about'><li>ABOUT</li></Link>
            <Link href='/blog'><li>BLOG</li></Link>
            <Link href='/contact'><li>CONTACT</li></Link>
          </ul>
        </nav>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Foody
          </p>
        </div>
        <div className={styles.blogs}>
          <h1>Popular Blog </h1>
          <div className={styles.blogItem}>
            <h3>Ganpat Chat Bhandar</h3>
            <p>This Shop is famous for Aloo Tikki</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  )
}