import Head from 'next/head'
import styles from '../styles/Home.module.css'

//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Foody</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span>
            FOODY
          </span>
        </h1>
        <div className={styles.description}>
          <p>
            A Blog for Foodies Person by Balram Kumar Gupta.
          </p>
        </div>
        <div className={styles.blogs}>
          <h1>Popular Blog </h1>
          <div className={styles.blogItem}>
            <h3>Ganpat Chat Bhandar</h3>
            <p>This Shop is famous for Aloo Tikki</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  )
}